Auto scaler profile fixes
claranet/terraform-azurerm-aks pull request #10
Opened 2023-02-17 06:22 UTC by oleksiimorozenko

This PR fixes the mismatch of the types of the dynamic `auto_scaler_profile` object

2023-02-17 13:52 UTC, oleksiimorozenko commented
Oh sorry, it was accidentally

2023-02-18 00:14 UTC, oleksiimorozenko commented
I suppose it would be better to merge after merging [the previous PR](https://github.com/claranet/terraform-azurerm-aks/pull/9)

2023-02-21 07:51 UTC, jmapro requested changes

2023-02-21 07:51 UTC, jmapro commented on variables.tf
> +  })
Why removing all default values ? I think it's important to provide some default values applicable to most of workloads

2023-02-22 07:52 UTC, jmapro approved these changes
LGTM

2023-02-27 08:57 UTC, merged