Add more configuration options to cluster's node pools
claranet/terraform-azurerm-aks pull request #9
Opened 2023-02-13 06:03 UTC by oleksiimorozenko

This PR adds configurable node labels to both system and user node pools
Also, it enables custom Kubernetes versions for user node pools if available node types versions differ from cluster version
Lastly, it adds an option for creating spot node pools by configuring `priority = "Spot"` option (and `"kubernetes.azure.com/scalesetpriority" = "spot"` node label)

2023-02-13 07:57 UTC, BzSpi commented
Hello,

Thank you for your contribution, this is very well appreciated.

Regarding the content of the PR, either you should define the default value for new attributes in `local.default_agent_profile` or use `lookup` to access the value.

2023-02-16 19:19 UTC, oleksiimorozenko commented
Default locals' values would be better I guess

2023-02-18 00:13 UTC, oleksiimorozenko commented
This is the final version so far, tested, works correctly

2023-02-20 12:59 UTC, Shr3ps approved these changes

2023-02-21 07:48 UTC, jmapro requested changes

2023-02-21 07:48 UTC, jmapro commented on variables.tf
>    type        = list(any)
you may use a list of objects with the same content as for `default_node_pool `

2023-02-24 16:30 UTC, oleksiimorozenko commented
Any news on this?

2023-02-27 08:09 UTC, jmapro approved these changes
LGTM

2023-02-27 08:56 UTC, merged